- name: Install less and related programs (Arch Linux)
  become: true
  community.general.pacman:
    name:
      - less

- name: Set up less-related environment variables
  import_tasks: '{{ playbook_dir }}/roles/env/tasks/set.yml'
  vars:
    variables:
      - name: 'PAGER'
        value: 'less'
      - name: 'LESS'
        value: '--ignore-case --LONG-PROMPT --RAW-CONTROL-CHARS --chop-long-lines --hilite-unread'
      - name: 'LESS_TERMCAP_us'
        value: '$(tput smul)'
      - name: 'LESS_TERMCAP_so'
        value: '$(tput setaf 6; tput smso)'
      - name: 'LESS_TERMCAP_md'
        value: '$(tput bold; tput setaf 1)'
      - name: 'LESS_TERMCAP_ue'
        value: '$(tput sgr0)'
      - name: 'LESS_TERMCAP_me'
        value: '$(tput sgr0)'
      - name: 'LESS_TERMCAP_se'
        value: '$(tput sgr0)'
