# Below is my personal configuration, that does not include colorschemes.

env:
  # Use a special version of the `alacritty` terminfo, with the user
  # capabilities Emacs needs to show 24bit colors.
  TERM: alacritty-24bits

font:
  # Use the Source Code Pro family for fonts. Note that there is no need to
  # separately specify the bold, italic, or bold-italic fonts; they will be
  # derived from the normal font.
  normal:
    family: Source Code Pro

  # It seems that Alacritty uses very large fonts be defaults (not sure why, I'm
  # gessing something relating to the DPI but I am not sure), so the specified
  # size here is fairly small.
  size: 7.0

key_bindings:
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: C, mods: Control|Shift, action: Copy }
  - { key: Key0, mods: Control, action: ResetFontSize }
  - { key: Equals, mods: Control, action: IncreaseFontSize }
  - { key: Subtract, mods: Control, action: DecreaseFontSize }
