homebrew_prefix: '{{ ansible_env.HOME }}/.brew'
homebrew_install_path: '{{ homebrew_prefix }}/Homebrew'
homebrew_bin_path: '{{ homebrew_prefix }}/bin'
homebrew_directories:
  - Caskroom
  - Cellar
  - Frameworks
  - Homebrew
  - bin
  - etc
  - include
  - lib
  - opt
  - sbin
  - share
  - var
