- name: Install emacs and related programs (macOS)
  community.general.homebrew:
    name:
      - emacs

- name: Enable the emacs service (macOS)
  command: brew services start emacs
  register: result
  changed_when: '"Successfully started" in result.stdout'