- name: Import platform tasks (Arch Linux)
  import_tasks: archlinux.yml
  when: ansible_distribution == 'Archlinux'

- name: Link .xinitrc to $HOME
  file:
    src: '{{ role_path }}/files/.xinitrc'
    dest: '{{ ansible_env.HOME }}/.xinitrc'
    state: link

- name: Ensure $HOME/.config/bspwm exists
  file:
    path: '{{ ansible_env.HOME }}/.config/bspwm'
    state: directory

- name: Link bspwmrc into place
  file:
    src: '{{ role_path }}/files/bspwmrc'
    dest: '{{ ansible_env.HOME }}/.config/bspwm/bspwmrc'
    state: link
