- name: Install `bspwm`
  tags:
    - bspwm
    - package
  become: true
  pacman:
    name:
      - bspwm
    state: present

- name: Create bspwm directory
  tags:
    - bspwm
    - filesystem
  file:
    dest: "{{ bspwm_dir }}"
    state: directory

- name: Create symbolic link to configuration file
  tags:
    - bspwm
    - filesystem
  file:
    src: "{{ role_path }}/files/bspwmrc"
    dest: "{{ bspwm_dir }}/bspwmrc"
    state: link
