- name: Ensure joinpaths directory exists
  file:
    path: '{{ joinpaths_dir }}'
    state: directory

- name: Ensure joinpaths script exists
  file:
    src: '{{ role_path }}/files/joinpaths.sh'
    dest: '{{ joinpaths_script }}'
    state: link

- name: Import platform tasks (macOS)
  import_tasks: macos.yml
  when: ansible_distribution == 'MacOSX'