- name: Install `alacritty` and `alacritty-terminfo`
  tags:
    - alacritty
    - package
  become: true
  pacman:
    name:
      - alacritty
      - alacritty-terminfo
    state: present

- name: Create config directory
  tags:
    - alacritty
    - filesystem
  file:
    dest: "{{ alacritty_dir }}"
    state: directory

- name: Compile 24-bit color terminfos
  tags:
    - alacritty
    - filesystem
  vars:
    terminfo_dir: "{{ home }}/.terminfo"
  command: tic -x -o {{ terminfo_dir }} {{ item|quote }}
  args:
    creates: "{{ terminfo_dir }}/{{ item | basename | first }}/{{ item | basename | splitext | first }}"
  with_fileglob: "*.terminfo"

- name: Create directory for config fragments
  tags:
    - alacritty
    - filesystem
  file:
    dest: "{{ fragments_dir }}"
    state: directory

- name: Copy config and colorscheme file to fragments directory
  tags:
    - alacritty
    - filesystem
  vars:
    color_basename: "{{ base16_scheme }}{{ '-256' if base16_256 else '' }}"
  copy:
    src: "{{ item }}"
    dest: "{{ fragments_dir }}"
  loop:
    - config.yml
    - "colors/base16/colors/base16-{{ color_basename }}.yml"

- name: Concatenate config and colorscheme file
  tags:
    - alacritty
    - filesystem
  assemble:
    src: "{{ fragments_dir }}"
    dest: "{{ alacritty_dir }}/alacritty.yml"
