- name: Import platform tasks (macOS)
  import_tasks: macos.yml
  when: ansible_distribution == 'MacOSX'

- name: Ensure Go environment variables are set
  loop: '{{ go_env | dict2items }}'
  lineinfile:
    path: '{{ envensure_entries }}'
    line: 'export {{ item.key }}="{{ item.value }}"'
    create: true

- name: Ensure $GOPATH/bin is included in $PATH
  lineinfile:
    path: '{{ pathensure_entries }}'
    line: '10 {{ go_env.GOPATH }}/bin'
    create: true

- name: Install Go tools using `go get`
  loop:
    - golang.org/x/tools/gopls
    - mvdan.cc/gofumpt/gofumports
  command:
    cmd: 'go get {{ item }}'
    creates: '{{ go_env.GOPATH }}/bin/{{ item.split("/")[-1] }}'
  environment: '{{ go_env }}'
