- name: Import platform tasks (Arch Linux)
  import_tasks: archlinux.yml
  when: ansible_distribution == 'Archlinux'

- name: Ensure the ~/.ssh directory exists
  file:
    path: '{{ ansible_env.HOME }}/.ssh'
    state: directory

- name: Link the SSH config into place
  file:
    src: '{{ role_path }}/files/config'
    dest: '{{ ansible_env.HOME }}/.ssh/config'
    state: link
