- name: Install zsh and related programs (Arch Linux)
  become: true
  community.general.pacman:
    name:
      - zsh

- name: Set login shell to /usr/bin/zsh (Arch Linux)
  become: true
  user:
    name: '{{ ansible_env.USER }}'
    shell: /usr/bin/zsh

