# No installation configured yet since I'm not running in on macOS yet, but
# probably it'll look something like this, based on the current (2025-08-29)
# README of Spacemacs:
#
# - name: Add Homebrew tap for Emacs Plus (macOS)
#   community.general.homebrew_tap:
#     name:
#       - d12frosted/emacs-plus
#
# - name: Install Emacs Plus (macOS)
#   community.general.homebrew_tap:
#     name:
#       - emacs-plus
#     install_options:
#       - with-spacemacs-icon
#       - with-native-comp
