- name: Ensure sxhkd configuration dir exists
  file:
    path: '{{ sxhkd_config_dir }}'
    state: directory

- name: Ensure sxhkd fragments dir exists
  file:
    path: '{{ sxhkd_fragments_dir }}'
    state: directory

- name: Set sxhkd keybindings
  import_tasks: '{{ playbook_dir }}/roles/sxhkd/tasks/keybindings.yml'
  vars:
    keybindings:
      - comment: 'Reload sxhkd configuration.'
        chord: 'super + r'
        command: 'pkill -USR1 -x sxhkd'
