- name: Import platform tasks (macOS)
  import_tasks: macos.yml
  when: ansible_distribution == 'MacOSX'

- name: Import platform tasks (Arch Linux)
  import_tasks: archlinux.yml
  when: ansible_distribution == 'Archlinux'

- name: Ensure Go environment variables are set
  import_tasks: '{{ playbook_dir }}/roles/env/tasks/set.yml'
  vars:
    variables: '{{ go_env | dict2items(key_name="name", value_name="value") }}'

- name: Ensure $GOPATH/bin is included in $PATH
  lineinfile:
    path: '{{ pathensure_entries }}'
    line: '10 {{ go_env.GOPATH }}/bin'
    create: true

- name: Install Go tools using `go get`
  loop:
    - golang.org/x/tools/gopls
    - mvdan.cc/gofumpt/gofumports
  command:
    cmd: 'go get {{ item }}'
    creates: '{{ go_env.GOPATH }}/bin/{{ item.split("/")[-1] }}'
  environment: '{{ go_env }}'
