- name: Install GNOME and GDM
  become: true
  community.general.pacman:
    name:
      - gnome

- name: Enable GDM
  become: true
  ansible.builtin.service:
    name: gdm.service
    enabled: true

- name: Enable NetworkManager (used by GNOME for networks)
  become: true
  ansible.builtin.service:
    name: NetworkManager.service
    enabled: true

- name: Install python-psutil, needed for dconf modification
  become: true
  community.general.pacman:
    name:
      - python-psutil

- name: Swap Caps Lock and Escape
  become: true
  become_user: '{{ arch_user }}'
  community.general.dconf:
    key: "/org/gnome/desktop/input-sources/xkb-options"
    value: "['caps:escape']"

- name: Enble battery percentage
  become: true
  become_user: '{{ arch_user }}'
  community.general.dconf:
    key: "/org/gnome/desktop/interface/show-battery-percentage"
    value: "true"

- name: Enable automatic time zone
  become: true
  become_user: '{{ arch_user }}'
  community.general.dconf:
    key: "/org/gnome/desktop/datetime/automatic-timezone"
    value: "true"

- name: Disable natural scrolling
  become: true
  become_user: '{{ arch_user }}'
  community.general.dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll"
    value: "false"

- name: Super+Enter to maximize windows
  become: true
  become_user: '{{ arch_user }}'
  community.general.dconf:
    key: "/org/gnome/desktop/wm/keybindings/maximize"
    value: "['<Super>Return']"
