- name: Install GNOME and GDM
  become: true
  community.general.pacman:
    name:
      - gnome

- name: Enable GDM
  become: true
  ansible.builtin.service:
    name: gdm.service
    enabled: true

- name: Install python-psutil, needed for dconf modification
  become: true
  community.general.pacman:
    name:
      - python-psutil

- name: Swap Caps Lock and Escape
  become: true
  become_user: '{{ arch_user }}'
  community.general.dconf:
    key: "/org/gnome/desktop/input-sources/xkb-options"
    value: "['caps:escape']"
