zsh_env:
  ZPLUG_HOME: '{{ ansible_env.HOME }}/.zplug'
  ZSHALIASES: '{{ ansible_env.HOME }}/.zsh-aliases'
  ZSHEXTRAS: '{{ ansible_env.HOME }}/.zsh-extras'
  ZSHPLUGINS: '{{ ansible_env.HOME }}/.zsh-plugins'
