- name: Import platform tasks (macOS)
  import_tasks: macos.yml
  when: ansible_distribution == 'MacOSX'

- name: Import platform tasks (Arch Linux)
  import_tasks: archlinux.yml
  when: ansible_distribution == 'Archlinux'

- name: Ensure .tmux.conf is in place
  file:
    src: '{{ role_path }}/files/.tmux.conf'
    dest: '{{ ansible_env.HOME }}/.tmux.conf'
    state: link

- name: Set up tmux aliases
  import_tasks: '{{ playbook_dir}}/roles/zsh/tasks/alias.yml'
  vars:
    aliases:
      't': 'tmux'
      'tn': 't new -s'
      'ta': 't attach'
      'tat': 'ta -t' # attach to session name
      'tl': 't list-sessions'
