- name: Install git and related programs (Arch Linux)
  become: true
  community.general.pacman:
    name:
      - git
      - git-branchless # https://github.com/arxanas/git-branchless
      - diff-so-fancy
