- name: Install git and related programs (Arch Linux)
  become: true
  community.general.pacman:
    name:
      - git
      - diff-so-fancy

- name: Symlink .gitconfig
  file:
    src: '{{ role_path }}/files/.gitconfig'
    dest: '{{ ansible_env.HOME }}/.gitconfig'
    state: link

- name: Set up git aliases
  ansible.builtin.file:
    src: '{{ role_path }}/files/aliases.zsh'
    dest: '{{ zsh_env.ZSHALIASES }}/git.zsh'
    state: link
