- name: Install firefox and related programs (Arch Linux)
  become: true
  community.general.pacman:
    name:
      - firefox

- name: Add firefox keybindings
  import_tasks: '{{ playbook_dir }}/roles/sxhkd/tasks/keybindings.yml'
  vars:
    keybindings:
      - comment: 'Start a Firefox browser window.'
        chord: 'super + w'
        command: 'firefox'
