#!/usr/bin/zsh
set -e
set -u
set -o pipefail

if [[ "$BLUETOOTH_PHONES_MAC" = "" ]]; then
    echo "No MAC address defined!"
    exit 1
fi

echo "info $BLUETOOTH_PHONES_MAC" | bluetoothctl | grep "Connected: yes" >/dev/null
