#!/bin/sh

# Start my simple "Keyboard Pilot" script.
bspc subscribe all | \
    keyboard-pilot \
        --config-file ${HOME}/.keyboard_pilot.json \
        1>${HOME}/.logs/keyboard_pilot.log \
        2>${HOME}/.logs/keyboard_pilot.err &

# Start my status bar.
${HOME}/.config/polybar/launch.sh

# Enable click to focus using `button1`.
bspc config click_to_focus button1

# Set up 5 desktops for each monitor, and be (at least fairly) sure that the
# names are unique.
for monitor in $(bspc query --monitors); do
    bspc monitor "${monitor}" --reset-desktops \
        "${monitor}_1" \
        "${monitor}_2" \
        "${monitor}_3" \
        "${monitor}_4" \
        "${monitor}_5"
done
