#!/bin/sh

# Start my simple "Keyboard Pilot" script.
bspc subscribe all | keyboard-pilot ${HOME}/.keyboard_pilot.json &

# Start my status bar.
${HOME}/.config/polybar/launch.sh

# Set up 5 desktops for each monitor, and be (at least fairly) sure that the
# names are unique.
for monitor in $(bspc query --monitors); do
    bspc monitor "${monitor}" --reset-desktops \
	    "${monitor}_1" \
	    "${monitor}_2" \
	    "${monitor}_3" \
	    "${monitor}_4" \
	    "${monitor}_5"
done

# Allow clicking to focus windows.
bspc config click_to_focus true
