- name: Install commonly needed or forgotten packages
  become: yes
  community.general.pacman:
    name:
      - man-db
      - inetutils # required for ansible.builtin.hostname
      - zsh # needed to set the user's shell, but configured in its own role
      - networkmanager
      - sudo

###############################################################################
# Tasks to set time-related options.
###############################################################################

- name: Enable the timesyncd service
  become: true
  ansible.builtin.service:
    name: systemd-timesyncd
    state: started
    enabled: true

- name: Set timezone
  become: true
  community.general.timezone:
    name: 'Europe/Dublin'

- name: Run timedatectl
  ansible.builtin.command:
    cmd: timedatectl status
  register: timedatectl_status
  changed_when: false

- name: Set system clock synchronization
  become: true
  ansible.builtin.command:
    cmd: hwclock --systohc --utc
  when: "'System clock synchronized: yes' not in timedatectl_status.stdout"

###############################################################################
# Tasks to set various options.
###############################################################################

- name: Set hostname
  become: yes
  ansible.builtin.hostname:
    name: 'arch'
    use: systemd

- name: Enable en_US.UTF-8 locale
  become: yes
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present

- name: Set LANG=en_US.UTF-8 in /etc/locale.conf
  become: yes
  ansible.builtin.copy:
    dest: /etc/locale.conf
    content: |
      LANG=en_US.UTF-8
      LANGUAGE=en_US.UTF-8

- name: Create user
  become: yes
  ansible.builtin.user:
    name: '{{ arch_user }}'
    groups: wheel
    append: true
    shell: /usr/bin/zsh

- name: Make wheel members allowed to run sudo
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^\# %wheel ALL=\(ALL\) ALL$'
    line: '%wheel ALL=(ALL) ALL'
    validate: 'visudo --check --file=%s'
