- name: Import platform tasks (macOS)
  import_tasks: macos.yml
  when: ansible_distribution == 'MacOSX'

- name: Import platform tasks (Arch Linux)
  import_tasks: archlinux.yml
  when: ansible_distribution == 'Archlinux'

- name: Symlink `.gitconfig` to $HOME
  file:
    src: '{{ role_path }}/files/.gitconfig'
    dest: '{{ ansible_env.HOME }}/.gitconfig'
    state: link
