- hosts: localhost
  connection: local
  roles:
    - alacritty
    - bspwm
    - emacs
    - firefox
    - fzf
    - git
    - go
    - iosevka
    - less
    - ranger
    - ripgrep
    - ssh
    - tmux
    - utils
    - zsh
