- name: Ensure path entries exist for default directories (macOS)
  import_tasks: '{{ playbook_dir }}/roles/path/tasks/set.yml'
  vars:
    priority: 90
    entries:
      - '/usr/local/bin'
      - '/usr/bin'
      - '/bin'
      - '/usr/sbin'
      - '/sbin'
