- name: Install emacs and related programs (Arch Linux)
  become: true
  community.general.pacman:
    name:
      - emacs

- name: Enable the Emacs systemd service (Arch Linux)
  ansible.builtin.systemd:
    name: emacs.service
    enabled: true
    scope: user
    state: started
