- name: Install emacs and related programs (Arch Linux)
  become: true
  community.general.pacman:
    name:
      - emacs

- name: Enable the Emacs systemd service (Arch Linux)
  ansible.builtin.systemd:
    name: emacs.service
    enabled: true
    scope: user
    state: started

- name: Set $EDITOR to `emacsclient`
  lineinfile:
    path: '{{ envensure_entries }}'
    line: 'export EDITOR=emacsclient'
    create: true
