- name: Install emacs and related programs (Arch Linux)
  become: true
  community.general.pacman:
    name:
      - emacs

- name: Enable the Emacs systemd service (Arch Linux)
  ansible.builtin.systemd:
    name: emacs.service
    enabled: true
    scope: user
    state: started

- name: Add emacs keybindings
  import_tasks: '{{ playbook_dir }}/roles/sxhkd/tasks/keybindings.yml'
  vars:
    keybindings:
      - comment: 'Start an Emacs client in a new frame.'
        chord: 'super + e'
        command: 'emacsclient -c'
