- name: Import platform tasks (Arch Linux)
  import_tasks: archlinux.yml
  when: ansible_distribution == 'Archlinux'

- name: Ensure alacritty config dir exists
  file:
    path: '{{ alacritty_config_dir }}'
    state: directory

- name: Ensure alacritty fragments dir exists
  file:
    path: '{{ alacritty_fragments_dir }}'
    state: directory

- name: Link configuration to fragments directory
  file:
    src: '{{ role_path }}/files/config.yml'
    dest: '{{ alacritty_fragments_dir }}/config.yml'
    state: link

- name: Link colorscheme to fragments directory
  file:
    src: '{{ role_path }}/files/base16-alacritty/colors/base16-{{ base16_colorscheme }}{{ "-256" if base16_256 else "" }}.yml'
    dest: '{{ alacritty_fragments_dir }}/colorscheme.yml'
    state: link

- name: Concatenate config and colorscheme
  assemble:
    src: '{{ ansible_env.HOME }}/.config/alacritty/fragments'
    dest: '{{ ansible_env.HOME }}/.config/alacritty/alacritty.yml'

- name: Add alacritty keybindings
  import_tasks: '{{ playbook_dir }}/roles/sxhkd/tasks/keybindings.yml'
  vars:
    keybindings:
      - comment: 'Start an Alacritty terminal.'
        chord: 'super + Return'
        command: 'alacritty'
  when: ansible_distribution == 'Archlinux'
