- name: Install alacritty and related programs (Arch Linux)
  become: true
  community.general.pacman:
    name:
      - alacritty

- name: Ensure alacritty config dir exists
  become: true
  become_user: '{{ arch_user }}'
  ansible.builtin.file:
    path: '{{ alacritty_config_dir }}'
    state: directory

- name: Ensure alacritty fragments dir exists
  become: true
  become_user: '{{ arch_user }}'
  ansible.builtin.file:
    path: '{{ alacritty_fragments_dir }}'
    state: directory

- name: Link configuration to fragments directory
  become: true
  become_user: '{{ arch_user }}'
  ansible.builtin.copy:
    src: '{{ role_path }}/files/config.toml'
    dest: '{{ alacritty_fragments_dir }}/config.toml'

- name: Link colorscheme to fragments directory
  become: true
  become_user: '{{ arch_user }}'
  ansible.builtin.copy:
    src: '{{ role_path }}/files/base16-alacritty/colors/base16-{{ base16_colorscheme }}{{ "-256" if base16_256 else "" }}.toml'
    dest: '{{ alacritty_fragments_dir }}/colorscheme.toml'

- name: Concatenate config and colorscheme
  become: true
  become_user: '{{ arch_user }}'
  ansible.builtin.assemble:
    src: '{{ alacritty_fragments_dir }}'
    dest: '{{ alacritty_config_dir }}/alacritty.toml'
