- name: Import platform tasks (macOS)
  import_tasks: macos.yml
  when: ansible_distribution == 'MacOSX'

- name: Ensure startup files are in place
  loop:
    - '.prompt'
    - '.zshrc'
  file:
    src: '{{ role_path }}/files/{{ item }}'
    dest: '{{ ansible_env.HOME }}/{{ item }}'
    state: link
