- name: Render shell template
  template:
    src: '{{ playbook_dir }}/roles/env/templates/shell.sh.j2'
    dest: '{{ env_dotd_dir }}/{{ role_name }}.sh'

- name: Render systemd template
  when: ansible_distribution == 'Archlinux'
  template:
    src: '{{ playbook_dir }}/roles/env/templates/systemd.conf.j2'
    dest: '{{ env_systemd_dir }}/{{ role_name }}.conf'
